name: Release

on:
  workflow_dispatch: # 手动触发
  push:
    tags:
      - 'v*.*.*' # 当推送符合版本模式的标签时触发
    paths-ignore:
      - '**/*.md' # 忽略 Markdown 文件的变更

jobs:

  build-and-release:
    if: "!contains(github.ref, '.beta')" # 排除包含 .beta 的标签
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码，获取完整的 Git 历史记录
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. 设置 Go 版本为 1.22
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # 3. 运行 GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest # 安装最新版本的 GoReleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.BDPCS_TOKEN }}
